### ISSUE TITLE
Error following tutorial

### ISSUE THREAD

**Issue by sajal** [valory-xyz/hello-world#16]
### Subject of the issue
Error while following the [step-by-step tutorial](https://docs.autonolas.network/open-autonomy/guides/quick_start/#step-by-step-instructions).

### Your environment
- OS: Ubuntu 22.04.4 LTS
- Python version: 3.10.12
- Package Version 0.1.0
- Anything else you consider helpful.
```
$ docker info
Client: Docker Engine - Community
 Version:    25.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.5
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 9
  Running: 0
  Paused: 0
  Stopped: 9
 Images: 18
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.2.0-34-generic
 Operating System: Ubuntu 22.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 29.09GiB
 Name: sajal-thinkpad
 ID: REMOVED
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Steps to reproduce
Follow the [setup](https://docs.autonolas.network/open-autonomy/guides/set_up/) and [quick start](https://docs.autonolas.network/open-autonomy/guides/quick_start/) guides

### Expected behaviour
The quick start guide should work as described

### Actual behaviour
 I encounter an error on step 3d

```
(auto) sajal@sajal-thinkpad:/tmp/auto/hello_world$ autonomy deploy build keys.json -ltm
Building deployment @ /tmp/auto/hello_world/abci_build
WARNING: `dependencies` parameter not defined in the service
Traceback (most recent call last):
  File "/home/sajal/.local/share/virtualenvs/auto-817pgp6H/bin/autonomy", line 8, in <module>
    sys.exit(cli())
  File "/home/sajal/.local/share/virtualenvs/auto-817pgp6H/lib/python3.10/site-packages/click/core.py", line 1126, in __call__
    return self.main(*args, **kwargs)
  File "/home/sajal/.local/share/virtualenvs/auto-817pgp6H/lib/python3.10/site-packages/click/core.py", line 1051, in main
    rv = self.invoke(ctx)
  File "/home/sajal/.local/share/virtualenvs/auto-817pgp6H/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sajal/.local/share/virtualenvs/auto-817pgp6H/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sajal/.local/share/virtualenvs/auto-817pgp6H/lib/python3.10/site-packages/click/core.py", line 1393, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sajal/.local/share/virtualenvs/auto-817pgp6H/lib/python3.10/site-packages/click/core.py", line 752, in invoke
    return __callback(*args, **kwargs)
  File "/home/sajal/.local/share/virtualenvs/auto-817pgp6H/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sajal/.local/share/virtualenvs/auto-817pgp6H/lib/python3.10/site-packages/autonomy/cli/deploy.py", line 258, in build_deployment_command
    build_deployment(
  File "/home/sajal/.local/share/virtualenvs/auto-817pgp6H/lib/python3.10/site-packages/autonomy/cli/helpers/deployment.py", line 213, in build_deployment
    report = generate_deployment(
  File "/home/sajal/.local/share/virtualenvs/auto-817pgp6H/lib/python3.10/site-packages/autonomy/deploy/build.py", line 89, in generate_deployment
    deployment.generate(
  File "/home/sajal/.local/share/virtualenvs/auto-817pgp6H/lib/python3.10/site-packages/autonomy/deploy/generators/docker_compose/base.py", line 260, in generate
    network = Network(name=network_name)
  File "/home/sajal/.local/share/virtualenvs/auto-817pgp6H/lib/python3.10/site-packages/autonomy/deploy/generators/docker_compose/base.py", line 177, in __init__
    self.subnet = self.build()
  File "/home/sajal/.local/share/virtualenvs/auto-817pgp6H/lib/python3.10/site-packages/autonomy/deploy/generators/docker_compose/base.py", line 203, in build
    for config in network.attrs["IPAM"]["Config"]:
TypeError: 'NoneType' object is not iterable
```

**Comment by sajal** [comment]
As explained in discord, current version only supports docker version <25. Worked fine for me after downgrading to docker 24.0.9 . Apparently support for docker 25 is coming soon.
